apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels:
     app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  temlate:
    metadata:
      labels:
        app: nginx
    spec:
      container: 
       -name: nginx
       image: nginx
       ports:
        -containerPort: 80 
