# Service Template with NodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
   - name: http
     port: 80
     nodePort: 30007
  selector:
    app: nginx
  type: NodePort